development:
    adapter: postgresql
    encoding: unicode
    database: store_development
    host: localhost
    pool: 5
    username: dawnzhao
    password:
        
test:
    adapter: postgresql
    encoding: unicode
    database: store_test
    host: localhost
    pool: 5
    username: dawnzhao
    password: